### ISSUE TITLE
Grbl Plugin printer octoprint (laser cutter)

### ISSUE THREAD

**Issue by arnoakavdb** [xZetsubou/ha-threedy-card#12]
Hi,
I'm using ocotprint with grbl plugin to control a laser cutting/engraving machine. I try to use the card with the ocotprint with no luck but the information come good in the ocotprint device inside home assistant (see picture below).Can i do something to force the card to read the information ?
![mecpow](https://github.com/xZetsubou/ha-threedy-card/assets/38015866/dd25880e-f391-4ae1-a86b-36466a356bb2)

**Comment by xZetsubou** [comment]
Try assigning the sensor manually instead of relying on the `base_entity` 

_note that this is only available with yaml mode only_ 
e.g.
```yml
# << configs
# Rather then specify 'base_entity' you can config each sensor.
type: 'custom:threedy-card'
base_entity: '' # You can use it if you want to override some of sensors and let some use base_etntity
name: 'Ender 3 Pro'
printer_type: I3
monitored:
  - Status
  - ETA
  - Elapsed
  - Remaining
  - Hotend
  - Bed
sensors:
  Progress: # return the print progress | 0 - 100
    entity: sensor.octoprint_print_progress 
  Elapsed: # return how much time have been since print starts - Require Status to be defined | number
    entity: sensor.octoprint_print_progress
    attribute: printTime 
  Remaining: # return how much time left to finish print - Require Status to be defined | number
    entity: sensor.octoprint_print_progress
    attribute: printTimeLeft
    name: Rem
  ETA: # return how much time left to finish print - Require Status to be defined | number
    entity: sensor.octoprint_print_progress
    attribute: printTimeLeft 
  Status: # return the state of printer | ( printing, stopped etc.. ) 
    entity: sensor.octoprint_print_status
  Hotend: # Return the temperature of hotend | number
    entity: sensor.octoprint_tool_0_temperature
  Bed: # Return the temperature of Bed | number
    entity: sensor.octoprint_bed_temperature
```
