### ISSUE TITLE
sensor override not working (ETA, Remaining and FileName are broken)

### ISSUE THREAD

**Issue by Kappawaii** [xZetsubou/ha-threedy-card#14]
After having issues on the original card, I tried this fork because users were reporting it as having fixed these sensor issues, but I'm experiencing the exact same issues : 
![image](https://github.com/user-attachments/assets/b2f7c581-cbb6-462f-935d-3fc91a97aa86)

Here's my card. I have Octoprint (1.10.3) on latest version with latest version of the HA discovery plugin (v3.7.0) and MQTT (0.8.16). HA is also on latest version (2024.11.2)
```
cards:
      - type: horizontal-stack
        cards:
          - type: custom:threedy-card
            base_entity: sensor.octoprint
            monitored:
              - Hotend
              - Bed
              - ETA
              - Remaining
              - Status
              - FileName
            printer_type: I3
            name: Ender 3
            theme: Default
            temperature_unit: C
            round_temperature: true
            use_mqtt: true
            scale: 1
            round_time: false
            use_24hr: true
            camera_entity: camera.octoprint_camera
            sensors:
              FileName:
                name: FileName
                entity: sensor.octoprint_print_file
              Elapsed:
                entity: sensor.octoprint_print_progress
                attribute: PrintTime
              Remaining:
                entity: sensor.octoprint_print_time_left
              Progress:
                entity: sensor.octoprint_print_progress
              ETA:
                entity: sensor.octoprint_print_progress
                attribute: printTimeLeft
              Status:
                entity: sensor.octoprint_print_status
              Hotend:
                entity: sensor.octoprint_tool_0_temperature
              Bed:
                entity: sensor.octoprint_bed_temperature
```
