### ISSUE TITLE
Camera SIze

### ISSUE THREAD

**Issue by Guenni75** [xZetsubou/ha-threedy-card#15]
After a minute, the camera picture doesn't fit into the card.
You have to reload the website. After that it works for a minute again.

![image](https://github.com/user-attachments/assets/a1839a8f-d4a8-4560-a743-bcdcd028bd95)

![image](https://github.com/user-attachments/assets/8973f097-8186-4308-8531-e7eaf3d22885)

**Comment by xZetsubou** [comment]
post the config yaml for the card.

**Comment by broyuken** [comment]
Mine does that too, here is the code for the card. Please reopen this.
```
type: custom:threedy-card
base_entity: ""
name: Ender 3 Pro
printer_type: I3
camera_entity: camera.klipper_ender3v3se_camera
monitored:
  - Status
  - FileName
  - ETA
  - Elapsed
  - Remaining
  - Hotend
  - Bed
sensors:
  Progress:
    entity: sensor.klipper_progress
  Status:
    entity: sensor.klipper_printer_state
  Elapsed:
    entity: sensor.klipper_print_duration
  Remaining:
    entity: sensor.klipper_slicer_print_time_left_estimate
  ETA:
    entity: sensor.klipper_slicer_print_time_left_estimate
  Hotend:
    entity: sensor.klipper_extruder_temperature
  Bed:
    entity: sensor.klipper_bed_temperature
  FileName:
    name: FileName
    entity: sensor.klipper_filename
```
