### ISSUE TITLE
can't get remaining time or ETA to work with Bambu lab sensor

### ISSUE THREAD

**Issue by jonathan-chin** [xZetsubou/ha-threedy-card#16]
I'm trying to use this awesome card with one of my Bambu's. it works perfectly for my other Octoprint managed printers, but I can't get remaining time or ETA. here's my config:

```
  - type: custom:threedy-card
    base_entity: sensor.x1c
    monitored:
      - Status
      - Remaining
      - Hotend
      - Bed
      - ETA
      - Elapsed
      - A
    sensors:
      Progress:
        entity: sensor.x1c_print_progress
      Status:
        entity: sensor.x1c_current_stage
      Hotend:
        entity: sensor.x1c_nozzle_temperature
      Bed:
        entity: sensor.x1c_bed_temperature
      Remaining:
        entity: sensor.x1c_remaining_time
      ETA:
        entity: sensor.x1c_end_time
    printer_type: I3
    name: x1c
    always_show: true
```

I've tried passing in `remaining_time`, which is a number measured in minutes, and `end_time`, which is a non standard timestamp string, into `Remaining`.  I even created a template that converted the non standard timestamp to a iso timestamp. but `Remaining` keeps printing out `-`. (I haven't tried as much with ETA but I imagine it's a related issue)

any idea on what could be going on here?
