### ISSUE TITLE
Add support for two hotends

### ISSUE THREAD

**Issue by alnavasa** [xZetsubou/ha-threedy-card#21]
Add support for two hot tends,and maybe also, add support to include units on custom sensors, 
I could do with just the last one. since I have just rebuilt the entire Ultimaker integration (waiting to do a PR to the actual one)
I want to leave it useful with this card straight away, The printer does have two hotness and two entities:

```
type: custom:threedy-card
base_entity: ""
name: UMS5
printer_type: I3
camera_entity: camera.ums5_camera
power_entity: switch.sonoff_10021d645b_1
light_entity: switch.sonoff_10021d645b_1
always_show: true
round_time: true
monitored:
  - Status


  - Elapsed
  - Remaining
  - Hotend 1
  - Hotend 2
  - Bed
sensors:
  Progress:
    entity: sensor.ums5_print_job_progress
  Status:
    entity: sensor.ums5_printer_activity
  Elapsed:

    entity: sensor.ums5_time_elapsed
  Remaining:
    entity: sensor.ums5_time_remaining
  Hotend 1:
    name: Hotend 1
    entity: sensor.ums5_hotend_1_temperature
  Hotend 2:
    name: Hotend 2
    entity: sensor.ums5_hotend_2_temperature
  Bed:
    entity: sensor.ums5_bed_temperature
  FileName:
    name: FileName
    entity: sensor.ums5_print_job_name
```
<img width="485" alt="Image" src="https://github.com/user-attachments/assets/509cdfcc-9e66-488b-aba9-360d15a2e8f7" />
