### ISSUE TITLE
Elapsed and Remaining sensors not showing in the card despite matching format

### ISSUE THREAD

**Issue by alnavasa** [xZetsubou/ha-threedy-card#22]
## Elapsed and Remaining sensors not showing in the card despite matching format

Hello 

First of all, thanks for your work on this card — it's visually impressive and a very intuitive way to monitor printers.

We’re integrating an Ultimaker printer using a custom integration that exposes the following `sensor` entities:

```yaml
sensor.ums5_time_elapsed_raw:
  state: 3491
  unit_of_measurement: "s"
  device_class: duration
  state_class: measurement

sensor.ums5_time_remaining_raw:
  state: 35242
  unit_of_measurement: "s"
  device_class: duration
  state_class: measurement
```

We also tried a version using hours instead of seconds:

```yaml
sensor.ums5_time_elapsed:
  state: 0.97
  unit_of_measurement: "h"
  device_class: duration
  state_class: measurement
```

Here is our card config:

```yaml
type: custom:threedy-card
name: UMS5
printer_type: I3
camera_entity: camera.ums5_camera
monitored:
  - Elapsed
  - Remaining
sensors:
  Elapsed:
    entity: sensor.ums5_time_elapsed_raw
  Remaining:
    entity: sensor.ums5_time_remaining_raw
```

---

### What we’ve confirmed

- Entity names are correct.
- Unit is provided as `"s"` and `"h"` in different tests.
- `device_class` is set to `duration`.
- `state_class` is `measurement`.
- `Status`, `Progress`, and `FileName` sensors show correctly.
- The raw values increase as expected during print.

---

### Issue

Despite all of the above, the `Elapsed` and `Remaining` fields do **not render** inside the card.

We inspected the code and found no specific documentation or fallback for these sensor names.

---

###  Request

Can you please check if:
- A specific naming format is required?
- A special state, attribute, or dependency must be fulfilled?
- The card logic expects different fields when `printer_type: I3` is used?

If required, we're happy to test or contribute with a PR.

Thanks again for the great work

**Comment by xZetsubou** [comment]
what is the status of the printer when it's printing this card only expect `printing` as a condition to show time. 
can you point me to the repo of the integration that you using as well.

**Comment by alnavasa** [comment]
it gives printing
yes

<img width="1272" alt="Image" src="https://github.com/user-attachments/assets/6c2dff20-bc99-4b96-8297-20d653f4e715" />
<img width="868" alt="Image" src="https://github.com/user-attachments/assets/2dce0ef4-0014-49ef-933e-1b75b24facd8" />


Code
```
type: custom:threedy-card
base_entity: 
name: UMS5
printer_type: I3
camera_entity: camera.ums5_camera
always_show: true
round_time: true
monitored:
  - Status
  - Elapsed
  - Remaining
  - ETA
  - Hotend 1
  - Hotend 2
  - Bed
sensors:
  Progress:
    entity: sensor.ums5_print_job_progress
  Status:
    entity: sensor.ums5_printer_activity
  ETA:
    entity: sensor.ums5_eta
  Elapsed:
    entity: sensor.ums5_time_elapsed_raw
  Remaining:
    entity: sensor.ums5_time_remaining_raw
  Hotend 1:
    name: Hotend 1
    entity: sensor.ums5_hotend_1_temperature
  Hotend 2:
    name: Hotend 2
    entity: sensor.ums5_hotend_2_temperature
  Bed:
    entity: sensor.ums5_bed_temperature
```
