### ISSUE TITLE
Custom Sensors

### ISSUE THREAD

**Issue by raddacle** [xZetsubou/ha-threedy-card#7]
I'm trying to use sensors that come from the moonraker integration, and I can't seem to get the syntax to make them appear according to your doc. All it shows is the printer name with a red dot next to it.

How off am I?

type: custom:threedy-card
base_entity: ''
monitored: ''
sensors:
  Filename: # return the print progress | 0 - 100
    entity: sensor.ender_3_s1_plus_filename
  Progress: # return the print progress | 0 - 100
    entity: sensor.ender_3_s1_plus_progress
name: Ender 3 S1 Plus
printer_type: I3

**Comment by xZetsubou** [comment]
Here is an example that I put in Readme. Copy it and paste in your card code. `red dot means you didn't provide status entity.`

assuming you are using [moonraker-homeassistant](https://github.com/marcolivierarsenault/moonraker-home-assistant/tree/9044226069b63782ef84922f7a20e2bf82b0a3f7) I'll try to guess the configs for you. this just guessing but as you can see set the sensors in `sensors` object then order them from `monitored` object.
```yaml
# Rather then specify 'base_entity' you can config each sensor.
type: 'custom:threedy-card'
base_entity: '' # You can use it if you want to override some of sensors and let some use base_etntity
name: 'Ender 3 S1 Plus'
printer_type: I3
monitored: # by the order you want.
  - Status
  - FileName
  - ETA
  - Elapsed
  - Remaining
  - Hotend
  - Bed
sensors:
  Progress: # return the print progress | 0 - 100
    entity: sensor.ender_3_s1_plus_progress 
  Status: # return the state of printer | ( printing, stopped etc.. ) 
    entity: sensor.ender_3_s1_current_print_state
  Elapsed: # return how much time have been since print starts - Require Status to be defined | number
    entity: sensor.ender_3_s1_print_duration
  Remaining: # return how much time left to finish print - Require Status to be defined | number
    entity: sensor.ender_3_s1_print_eta
  ETA: # return how much time left to finish print - Require Status to be defined | number
    entity: sensor.ender_3_s1_print_eta
  Hotend: # Return the temperature of hotend | number
    entity: sensor.ender_3_s1_extruder_temperature
  Bed: # Return the temperature of Bed | number
    entity: sensor.ender_3_s1_bed_temperature
  FileName:
    name: FileName
    entity: sensor.ender_3_s1_plus_filename
```
You should know that `Progress, Elapsed, Remaining, ETA, Status, Hotend and Bed` are the main sensors.
This how to specify an additional sensors: 
```yaml
monitored: # you need to add it into monitored as well.
  - sensor_name
sensors:
 sensor_name:
    entity: # the sensor entity
    name: # the name if you want
    attribute: # if the value is in attribute into the entity.
```

more [examples](https://github.com/xZetsubou/ha-threedy-card#examples)
