### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by simphide** [xZetsubou/ha-threedy-card#9]
Since two days I am getting the following error:
![image](https://github.com/xZetsubou/ha-threedy-card/assets/8183517/521e5863-4bcd-4566-b9dc-70cdde721025)

Downgrading didn't help.

Do you have a idea what the problem could be?

**Comment by xZetsubou** [comment]
Can you post your card `yaml` code. `probably because one of ETA, Remaining or Elapsed is incorrect`

**Comment by xZetsubou** [comment]
Mind to enable `beta` on HACS and try `2.1.8`, you need to select 2.1.8 manually as HACS won't auto select it

<details><summary>Enable beta</summary>
<p>

Go HACS -> Local Tuya -> On top right corner click on the ⋮ and redownload select latest beta -> restart HA.
`You need to select the latest beta version manually it HACS doesn't auto select it`

![image](https://github.com/xZetsubou/ha-threedy-card/assets/46300268/981cb333-a739-4f9a-b59d-8c6a40265df7)


</p>
</details>

**Comment by simphide** [comment]
For some reasons the beta version isn't shown at all:
<img width="514" alt="image" src="https://github.com/xZetsubou/ha-threedy-card/assets/8183517/607f7611-6088-435a-9efe-d435cfeb6e80">

I have reinstalled the card multiple times (via HACS) and tried to open the page with different browsers.

**Comment by xZetsubou** [comment]
Sorry, try again beta version should shows on HACS. I really recommend you to not rely on `base_entity` anymore as this card uses static `snesors names` and may be outdated and also this error probably because card couldn't found `ETA or Remaining` sensors.
instead override the sensors manually if it didn't works.

<details><summary>card yaml</summary>
<p>

```yaml
type: custom:threedy-card
always_show: true
base_entity: ''
printer_type: I3
name: Ender 3 Pro
camera_entity: camera.ender_3_pro_camera
power_entity: switch.ender3pro_plug
light_entity: light.ender3_printer
use_mqtt: true
monitored:
  - Status
  - ETA
  - Elapsed
  - Remaining
  - Hotend
  - Bed
round_temperature: true
round_time: true
camera_rotate: true
sensors:
  Progress:
    entity: sensor.octoprint_job_percentage
  Elapsed:
    entity: sensor.octoprint_start_time
  Remaining:
    entity: sensor.octoprint_estimated_finish_time
  ETA:
    entity: sensor.octoprint_estimated_finish_time
  Status:
    entity: sensor.octoprint_current_state
  Hotend:
    entity: sensor.octoprint_target_tool0_temp
  Bed:
    entity: sensor.octoprint_target_bed_temp
```

</p>
</details> 

I updated sensors names by if `ETA or Remaining or Elpased` failed in the future override them like the card config above :)
